/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author eva
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
JLabel lblPhone = new JLabel("Phone #");
    lblPhone.setBounds(65, 68, 46, 14);
    frame.getContentPane().add(lblPhone);
     
    textField_1 = new JTextField();
    textField_1.setBounds(128, 65, 86, 20);
    frame.getContentPane().add(textField_1);
    textField_1.setColumns(10);
     
    JLabel lblEmailId = new JLabel("Email Id");
    lblEmailId.setBounds(65, 115, 46, 14);
    frame.getContentPane().add(lblEmailId);
     
    textField_2 = new JTextField();
    textField_2.setBounds(128, 112, 247, 17);
    frame.getContentPane().add(textField_2);
    textField_2.setColumns(10);
     
    JLabel lblAddress = new JLabel("Address");
    lblAddress.setBounds(65, 162, 46, 14);
    frame.getContentPane().add(lblAddress);
             
    JTextArea textArea_1 = new JTextArea();
    textArea_1.setBounds(126, 157, 212, 40);
    frame.getContentPane().add(textArea_1);
     
     
     
    JButton btnClear = new JButton("Clear");
     
    btnClear.setBounds(312, 387, 89, 23);
    frame.getContentPane().add(btnClear);
     
    JLabel lblSex = new JLabel("Sex");
    lblSex.setBounds(65, 228, 46, 14);
    frame.getContentPane().add(lblSex);
     
    JLabel lblMale = new JLabel("Male");
    lblMale.setBounds(128, 228, 46, 14);
    frame.getContentPane().add(lblMale);
     
    JLabel lblFemale = new JLabel("Female");
    lblFemale.setBounds(292, 228, 46, 14);
    frame.getContentPane().add(lblFemale);
     
    JRadioButton radioButton = new JRadioButton("");
    radioButton.setBounds(337, 224, 109, 23);
    frame.getContentPane().add(radioButton);
     
    JRadioButton radioButton_1 = new JRadioButton("");
    radioButton_1.setBounds(162, 224, 109, 23);
    frame.getContentPane().add(radioButton_1);
     
    JLabel lblOccupation = new JLabel("Occupation");
    lblOccupation.setBounds(65, 288, 67, 14);
    frame.getContentPane().add(lblOccupation);
     
    JComboBox comboBox = new JComboBox();
    comboBox.addItem("Select");
    comboBox.addItem("Business");
    comboBox.addItem("Engineer");
    comboBox.addItem("Doctor");
    comboBox.addItem("Student");
    comboBox.addItem("Others");
    comboBox.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent arg0) {
        }
    });
    comboBox.setBounds(180, 285, 91, 20);
    frame.getContentPane().add(comboBox);
     
     
    JButton btnSubmit = new JButton("submit");
     
    btnSubmit.setBackground(Color.BLUE);
    btnSubmit.setForeground(Color.MAGENTA);
    btnSubmit.setBounds(65, 387, 89, 23);
    frame.getContentPane().add(btnSubmit);
 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
